PIVNET_TOKEN=sYXSBePuzmkr4jAJiZxC

VCENTER_HOST=172.16.1.2
VCENTER_USR=pivotal@homelab.io
VCENTER_PWD=Welcome12#
VCENTER_DATA_CENTER="PCF"

OM_DATA_STORE="PCF_STORAGE_1"
OPS_MGR_HOST=opsmgr.homelab.io
OPS_MGR_USR=admin
OPS_MGR_PWD=welcome
OPS_MGR_SSH_PWD=welcome
OM_DECRYPTION_PWD=welcome
OM_NTP_SERVERS=172.16.1.2
OM_DNS_SERVERS=172.16.1.2
OM_GATEWAY=172.16.0.1
OM_NETMASK=255.255.254.0
OM_IP=172.16.1.40

OM_VM_NETWORK="PCF_NW"
OM_VM_NAME="OpsManager"
OM_RESOURCE_POOL="/PCF/host/PCF_CLUSTER_1/Resources/MGMT_RP"
OM_DISK_TYPE="thick"
OM_VM_POWER_STATE=true
